### ISSUE TITLE
TypeError running tf-ema

### ISSUE THREAD

**Issue by ghost** [RuiShu/micro-projects#1]
Hi, RuiShu, 
 I tried to run the code tf-ema. It showed a bug like this:

{'design': 'v1', 'logdir': 'log', 'lr': 0.001, 'run': 999, 'src': 'cifar10'}
Model name: model=classifier_src=cifar10_design=v1_run=0999
Traceback (most recent call last):
  File "run_classifier.py", line 34, in <module>
    M = classifier()
  File "/home/leifan/micro-projects-master/tf-ema/codebase/models/classifier.py", line 32, in classifier
    src_y = des.classifier(T.src_x, T.phase, internal_update=True)
  File "/home/leifan/micro-projects-master/tf-ema/codebase/models/designs/v1.py", line 39, in classifier
    x = f(x, *f_args, **f_kwargs)
  File "/home/leifan/tensorflow/_python_build/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/leifan/.local/lib/python2.7/site-packages/tensorbayes/layers/simple.py", line 66, in conv2d
    initializer=tf.zeros_initializer)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 987, in get_variable
    custom_getter=custom_getter)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 889, in get_variable
    custom_getter=custom_getter)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 347, in get_variable
    validate_shape=validate_shape)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 332, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 683, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/leifan/tensorflow/_python_build/tensorflow/python/ops/variable_scope.py", line 672, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: zeros_initializer() got multiple values for keyword argument 'dtype'

**Comment by RuiShu** [comment]
I am not able to replicate your error. I'm using tensorbayes 0.3.0 and tensorflow 1.4.1

**Comment by ghost** [comment]
Hi, thank you for your timely reply. It was the version problem. I used python2.7.
I tried to run it with Python3. And here I found a new problem.
------------------------------------------------------------------------------------------
python3 run_classifier.py 
{'design': 'v1', 'logdir': 'log', 'lr': 0.001, 'run': 999, 'src': 'cifar10'}
Traceback (most recent call last):
  File "run_classifier.py", line 18, in <module>
    from codebase.models.classifier import classifier
  File "/home/leifan/micro-projects-master/tf-ema/codebase/models/classifier.py", line 7
    exec "from designs import {:s} as des".format(args.design)
                                                               ^
SyntaxError: invalid syntax
------------------------------------------------------------------------------------------------------------------
The syntaxError disappears when I run with Python2.7. So I think it is also a version problem.

**Comment by RuiShu** [comment]
> It was the version problem. I used python2.7.

I'm a little puzzled by your statement; are you saying that the TypeError was the result of using python 2.7?

As for the syntax error, this repo was written in 2.7 and uses 2.7 syntax for print and exec. You'll have to convert those into functions if using python 3.

**Comment by ghost** [comment]
Oh, it's my fault. I used an old version tensorflow with python2.7, then I switched to the 1.4.1 tensorflow with python3. 
It worked now. Thank you for your explanation.

**Comment by RuiShu** [comment]
Oh, gotcha. Glad things worked out!
